name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Write the private key to a temporary file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into the server and deploy
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@174.129.103.108 << 'EOF'
            # Navigate to the app directory and clean up old files
            cd /var/www/myapp
            sudo rm -rf build

            # Download the latest build artifact from JFrog
            ./jfrog rt dl "local/builds/react-app/build-${{ github.run_id }}/build.zip" .

            # Unzip the artifact and move it to the proper location
            unzip build.zip
            mv build/* .

            # Restart the nginx server
            sudo systemctl restart nginx
          EOF

      - name: Clean up private key
        run: rm private_key.pem
