name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install JFrog CLI
        run: curl -fL https://getcli.jfrog.io | sh

      - name: Configure JFrog CLI
        run: |
          ./jfrog rt config --url ${{ secrets.JFROG_URL }} \
                            --user ${{ secrets.JFROG_USERNAME }} \
                            --password ${{ secrets.JFROG_PASSWORD }}

      - name: Download artifact from JFrog
        run: |
          # Download the zip artifact
          ./jfrog rt download "local/builds/react-app/build-${{ github.event.workflow_run.id }}/build.zip" .

      - name: Unzip artifact
        run: |
          # Unzip the downloaded artifact
          unzip build.zip -d build

      - name: Deploy Application
        run: |
          # Move into the build directory and start your application
          cd build
          # Replace the following line with your deployment command
          # e.g., npm start, pm2 start, etc.
          echo "Deploying the application..."
