name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Write the private key to a temporary file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into the server and deploy
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@174.129.103.108 << 'EOF'
            cd /var/www/myapp
            sudo rm -rf build

            if ! command -v jfrog &> /dev/null; then
              curl -fL https://getcli.jfrog.io | sh
            fi

            # Download the build artifact using the run_id from CI
            ./jfrog rt dl "local/builds/react-app/build-${{ github.run_id }}/build.zip" . 
            unzip build.zip
            mv build/* .
            sudo systemctl restart nginx
          EOF

      - name: Clean up private key
        run: rm private_key.pem
