name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@174.129.103.108 << 'EOF'
          # Step 1: Update packages and ensure nginx and unzip are installed
          sudo apt-get update
          sudo apt-get install -y nginx unzip

          # Step 2: Download artifact from JFrog
          echo "Downloading artifact from: ${{ secrets.JFROG_URL }}/artifactory/local/builds/react-app/build-${{ github.event.workflow_run.head_run_id }}/"
          curl -u${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }} -L \
            "${{ secrets.JFROG_URL }}/artifactory/local/builds/react-app/build-${{ github.event.workflow_run.head_run_id }}/" -o build.zip

          # Step 3: Unzip downloaded artifact
          if [ -f build.zip ]; then
            unzip -o build.zip -d build/
          else
            echo "Download failed or file does not exist."
            exit 1
          fi

          # Step 4: Move the downloaded files to the deployment directory
          mv build/* /var/www/myapp/ || { echo "Move failed"; exit 1; }

          # Step 5: Restart Nginx to apply changes
          sudo nginx -t && sudo systemctl restart nginx || { echo "Nginx restart failed"; exit 1; }
        EOF
