name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.12'

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run tests
        run: pnpm test
      
      - name: Build
        run: pnpm build
      
      - name: Install JFrog CLI
        run: curl -fL https://getcli.jfrog.io | sh

      - name: Configure JFrog CLI
        run: |
          ./jfrog rt config --url ${{ secrets.JFROG_URL }} \
                            --user ${{ secrets.JFROG_USERNAME }} \
                            --password ${{ secrets.JFROG_PASSWORD }}

      - name: Zip build artifacts
        run: zip -r build.zip build/*

      - name: Upload artifact to JFrog
        run: ./jfrog rt upload "build.zip" "local/builds/react-app/build-${{ github.run_id }}/build.zip"
