name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.12'

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run tests
        run: pnpm test
      
      - name: Build
        run: pnpm build
      
      - name: Install JFrog CLI
        run: curl -fL https://getcli.jfrog.io | sh

      - name: Configure JFrog CLI
        run: |
          ./jfrog rt config --url ${{ secrets.JFROG_URL }} \
                            --user ${{ secrets.JFROG_USERNAME }} \
                            --password ${{ secrets.JFROG_PASSWORD }}

      - name: Zip build artifacts
        run: |
          # Check if the build directory exists and contains files
          if [ -d "build" ] && [ "$(ls -A build)" ]; then
            zip -r build.zip build/*
            echo "Build artifacts zipped successfully."
          else
            echo "Build directory is empty or does not exist."
            exit 1
          fi

      - name: Upload artifact to JFrog
        run: |
          # Check if the zip file was created
          if [ -f "build.zip" ]; then
            # Upload the zipped build artifact with a unique name based on the GitHub run ID
            ./jfrog rt upload "build.zip" "local/builds/react-app/build-${{ github.run_id }}/build.zip" || {
              echo "JFrog upload failed, exiting.";
              exit 1;
            }
            echo "Build artifact uploaded successfully to JFrog."
          else
            echo "build.zip does not exist, cannot upload.";
            exit 1
          fi
