name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, '[CI]')

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'v18.12'
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Run tests
      run: pnpm test
    - name: Build
      run: pnpm build